image: node:8.12.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run gitlab
  artifacts:
    paths:
      - public
  only:
    - my-custom-version
    - pages

